# Generated by Django 4.0.3 on 2022-03-10 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Seller', '0001_initial'),
        ('Customer', '0001_initial'),
        ('CustomerProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='accessories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.accessories'),
        ),
        migrations.AddField(
            model_name='order_item',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customer'),
        ),
        migrations.AddField(
            model_name='order_item',
            name='laptop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.laptop'),
        ),
        migrations.AddField(
            model_name='custorders',
            name='accessories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.accessories'),
        ),
        migrations.AddField(
            model_name='custorders',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CustomerProfile.address'),
        ),
        migrations.AddField(
            model_name='custorders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customer'),
        ),
        migrations.AddField(
            model_name='custorders',
            name='laptop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.laptop'),
        ),
    ]
